/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import java.awt.Component;
import java.awt.event.MouseEvent;

/**
 *
 * @author abugray
 */
public class MenuBar extends javax.swing.JFrame {

    /**
     * Creates new form MenuBar
     */
    public MenuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPopup = new javax.swing.JPopupMenu();
        undo = new javax.swing.JMenuItem();
        rendo = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        cat = new javax.swing.JMenuItem();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();
        pasteSpecial = new javax.swing.JMenu();
        pasteFormHistory = new javax.swing.JMenuItem();
        pasteAsColumn = new javax.swing.JMenuItem();
        duplicat = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        toolBar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        menuSeparator = new javax.swing.JPopupMenu.Separator();
        menuSetting = new javax.swing.JMenu();

        undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit-undo-symbolic.symbolic.png"))); // NOI18N
        undo.setText("Undo");
        menuPopup.add(undo);

        rendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit-undo-symbolic-rtl.symbolic.png"))); // NOI18N
        rendo.setText("Rendo");
        menuPopup.add(rendo);
        menuPopup.add(separator);

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit-cut-symbolic.symbolic.png"))); // NOI18N
        cat.setText("Cat");
        menuPopup.add(cat);

        copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit-copy-symbolic.symbolic.png"))); // NOI18N
        copy.setText("Copy");
        menuPopup.add(copy);

        paste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit-paste-symbolic.symbolic.png"))); // NOI18N
        paste.setText("Paste");
        menuPopup.add(paste);

        pasteSpecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/format-justify-fill-symbolic.symbolic.png"))); // NOI18N
        pasteSpecial.setText("Paste Special");

        pasteFormHistory.setText("Paste Form History");
        pasteSpecial.add(pasteFormHistory);

        pasteAsColumn.setText("Paste As Column");
        pasteSpecial.add(pasteAsColumn);

        menuPopup.add(pasteSpecial);

        duplicat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/document-new-symbolic.symbolic.png"))); // NOI18N
        duplicat.setText("Duplicat");
        menuPopup.add(duplicat);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit-delete-symbolic.symbolic.png"))); // NOI18N
        delete.setText("Delete");
        menuPopup.add(delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Project v.4");

        toolBar.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/abu.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        toolBar.add(jButton1);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        menuFile.setMnemonic('f');
        menuFile.setText("File");
        menuFile.setToolTipText("");

        menuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/document-new-symbolic.symbolic.png"))); // NOI18N
        menuNew.setText("New");
        menuFile.add(menuNew);

        Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/document-open-symbolic.symbolic.png"))); // NOI18N
        Open.setMnemonic('o');
        Open.setText("Open");
        menuFile.add(Open);

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/document-save-symbolic.symbolic.png"))); // NOI18N
        Save.setMnemonic('s');
        Save.setText("Save");
        menuFile.add(Save);
        menuFile.add(menuSeparator);

        menuSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/document-properties-symbolic.symbolic.png"))); // NOI18N
        menuSetting.setText("Setting");
        menuFile.add(menuSetting);

        menuBar.add(menuFile);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(680, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(evt.getButton()==MouseEvent.BUTTON3){
            menuPopup.show((Component)evt.getSource(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem cat;
    private javax.swing.JMenuItem copy;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem duplicat;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JPopupMenu menuPopup;
    private javax.swing.JPopupMenu.Separator menuSeparator;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JMenuItem paste;
    private javax.swing.JMenuItem pasteAsColumn;
    private javax.swing.JMenuItem pasteFormHistory;
    private javax.swing.JMenu pasteSpecial;
    private javax.swing.JMenuItem rendo;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JMenuItem undo;
    // End of variables declaration//GEN-END:variables
}
